#!/bin/sh
#
#  Copyright (c) 2020-2023 Masato Minda
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
#  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#  SUCH DAMAGE.

PATH=$PATH:/usr/local/sbin:/sbin:/usr/sbin

key='snapshot'

now=$(date +%Y%m%d%H%M%S)

while getopts 'rk:' cmd_arg; do
	case "${cmd_arg}" in
	r)      opt='-r';;
	k)      key="${OPTARG}";;
	esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
	echo "Usage: ${0##*/} [-r] [-k keyword] filesystem [filesystem ...]" >&2
	exit 1
fi

for fs
do
	[ "${fs}" = . ] && fs=$(df . | tail -1 | awk '{print $1}')
	zfs list "${fs}" >/dev/null 2>&1 || continue
	zfs snapshot ${opt} "${fs}"@"_${key}_${now}"
done
