#!/bin/sh

PATH=$PATH:/usr/local/sbin:/sbin:/usr/sbin

key='snapshot'

now=$(date +%Y%m%d%H%M%S)

while getopts 'rk:' cmd_arg; do
	case "${cmd_arg}" in
	r)      opt='-r';;
	k)      key="${OPTARG}";;
	esac
done
shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
	echo "Usage: ${0##*/} [-r] [-k keyword] filesystem [filesystem ...]" >&2
	exit 1
fi

for fs
do
	[ "${fs}" = . ] && fs=$(df . | tail -1 | awk '{print $1}')
	zfs list "${fs}" >/dev/null 2>&1 || continue
	zfs snapshot ${opt} "${fs}"@"_${key}_${now}"
done
